# Generated by Django 6.0.6 on 2026-07-19 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('registered', 'Registered'), ('logged_in', 'Logged in'), ('logged_out', 'Logged out'), ('profile_updated', 'Profile updated'), ('ai_chat', 'AI tutor question'), ('note_saved', 'Note saved'), ('quiz_saved', 'Quiz result saved'), ('resume_updated', 'Resume updated'), ('interview_completed', 'Interview completed')], max_length=40),
        ),
        migrations.CreateModel(
            name='AIChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
